export default function PrivacyNotice(){
 const contact=process.env.NEXT_PUBLIC_PRIVACY_CONTACT_EMAIL;
 const operator=process.env.NEXT_PUBLIC_PRIVACY_OPERATOR_NAME||'Elite Performance operator';
 return <main className="rc68Policy"><h1>Privacy Notice</h1><p>Version 2026-10-03 · Operator: {operator}</p>
 <h2>Information used for the app</h2><p>We collect account email and authentication information; Player names or chosen display names, age information, sport profiles, optional photos, team and family links, goals, testing, workouts, check-ins, reviews, schedules and information you choose to enter. Use only information needed for development. Do not enter identity documents, payment details or unnecessary medical information.</p>
 <h2>Who can access it</h2><p>Profiles are not a public directory. Access is limited by account and database permissions. Linked guardians can support their Players. Coaches receive access when an authorized adult or verified guardian joins a team. Admins have operational access for support and privacy requests. A person allowed to view information can copy or screenshot it; revocation cannot retrieve copies they already downloaded.</p>
 <h2>Service providers and outside resources</h2><p>Supabase processes authentication and stored app information. Vercel hosts the app. The configured transactional email provider delivers verification and password-reset messages. When inactivity automation is enabled, Resend processes recipient emails and generic inactivity warnings; those warnings contain no Player names, photos or training records. These providers process data to operate the service. We do not sell Player information, use it for advertising, share emails for marketing, or send Player records to AI services for training. Tracker connectivity and subscriptions are disabled.</p><p>Exercise demonstrations may link to external websites. Opening those links is optional and subjects the visit to that provider’s privacy practices. Profile photos are resized in your browser and stored with protected app records; public profile-image URLs are not used.</p>
 <h2>Minors and guardian authorization</h2><p>For our policy, a minor is anyone under 18. Junior Mode uses its existing age rules separately. Guardian verification and explicit authorization are required before opening a minor’s development workspace. An account checkbox alone does not establish verified guardian consent. Verification may use a reviewed consent form, documented verification call or approved verification provider. The operator must verify the method and guardian authority before recording approval.</p>
 <h2>Your choices</h2><p>Photos are optional. In the Privacy Center, authorized guardians and adult Players can download Player data, remove a photo, revoke Coach access, pause collection and withdraw consent. Resuming collection does not automatically restore Coach access. Deletion requires explicit confirmation. Shared guardian records need authority review; collection can be stopped immediately while review takes place.</p><p>Account deletion removes the requesting account, personal workspace and links. Other parents’ accounts and shared Players remain. Solely managed Players must be deleted or transferred first. A linked Player record must be deleted first, or resolved through a reviewed request. Privacy requests do not become deletion simply because an Admin changes a status label.</p>
 <h2>Inactivity</h2><p>When enabled by the operator, eligible accounts and Player records are deleted after 12 calendar months without activity. We send a warning after six months and a final warning 30 days before eligibility. Deletion waits at least 30 days after delivery of the final warning. A Player or any linked parent using the app resets that Player’s clock. Existing records receive a fresh clock when this policy is installed. Failed notices, guardian disputes, paused records and accounts whose deletion would leave Players without support require review. Admin accounts are excluded.</p><h2>Retention, devices and backups</h2><p>Confirmed deletion removes applicable active records and stored photo copies controlled by the app. It does not remove earlier downloads, screenshots or third-party copies outside our control. Local device data is cleared on logout and account changes. Open sessions periodically recheck access while online. Older app versions or offline devices may still contain previously cached information; update and clear those devices.</p><p>{process.env.NEXT_PUBLIC_PRIVACY_RETENTION_NOTE||'Contact the operator for the applicable record and backup retention schedule before providing Player data. The operator must publish a verified schedule before accepting minor records.'}</p>
 <h2>Contact and requests</h2>{contact?<p>Contact <a href={'mailto:'+contact}>{contact}</a> to review guardian authority, raise a privacy concern, request correction, withdrawal or reviewed deletion, or obtain the retention schedule.</p>:<p>Privacy contact has not been configured. The operator must configure a monitored privacy contact before collecting Player information.</p>}
 <p><a href="/terms">Terms of Use</a> · <a href="/">Return to app</a></p></main>
}
