"use client";
import {useEffect,useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
import {clearPrivateCache} from '../lib/privacy.mjs';
export type PrivacyStatus={paused:boolean;requiresGuardian:boolean;collectionAllowed:boolean;canControl:boolean;guardianVerified:boolean;parentCount:number;withdrawalByAnotherGuardian?:boolean};
type Props={client:SupabaseClient;role:string;athletes:{id:string;name:string}[];initialId?:string;onSignOut:()=>Promise<void>};
export default function PrivacyControls({client,role,athletes,initialId,onSignOut}:Props){
 const [id,setId]=useState(initialId||athletes[0]?.id||'');
 const [status,setStatus]=useState<PrivacyStatus|null>(null),[teams,setTeams]=useState<{team_id:string;team_name:string}[]>([]);
 const [message,setMessage]=useState(''),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(''),[password,setPassword]=useState('');
 const [retention,setRetention]=useState<{enabled:boolean;lastActivity:string}|null>(null);
 const [authorization,setAuthorization]=useState(false);
 useEffect(()=>{let alive=true;setStatus(null);setRetention(null);setTeams([]);setMessage('');
 if(id){client.rpc('retention_status',{p_athlete:id}).then(r=>{if(alive&&!r.error)setRetention(r.data)});Promise.all([client.rpc('privacy_status',{p_athlete:id}),client.rpc('privacy_access_summary',{p_athlete_id:id})]).then(([s,t])=>{
 if(!alive)return;if(s.error){setMessage('Privacy controls unavailable. Apply migration 017 before using this release.');return}setStatus(s.data);
 setTeams((Array.isArray(t.data)?t.data[0]:t.data)?.coach_access||[]);});}
 return()=>{alive=false};},[id,client]);
 const run=async(fn:()=>PromiseLike<{error:any}>,reload=true)=>{if(busy)return;setBusy(true);setMessage('');
 try{const r=await fn();if(r.error)throw new Error(r.error.message||'Privacy action failed');setMessage('Saved.');
 if(reload){clearPrivateCache(localStorage);clearPrivateCache(sessionStorage);window.location.reload();}}
 catch(e){setMessage(e instanceof Error?e.message:'Privacy action failed.')}finally{setBusy(false)}};
 const download=()=>void run(async()=>{const r=await client.rpc('privacy_export_player',{p_athlete:id});if(!r.error){const url=URL.createObjectURL(new Blob([JSON.stringify(r.data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='elite-performance-player-export.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}return r},false);
 const deleteAccount=()=>void run(async()=>{const r=await client.functions.invoke('privacy-account-delete',{body:{password,confirmation:confirm}});setPassword('');if(r.data?.error&&!r.error)return {error:{message:r.data.error}};if(!r.error)await onSignOut();return r},false);
 return <section className="rc68PrivacyControls"><h3>Parent and Player controls</h3>
 {athletes.length>0&&<label>Player<select value={id} onChange={e=>{setId(e.target.value);setConfirm('');setAuthorization(false)}}>{athletes.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>}
 {role==='Parent'&&!status?.guardianVerified&&<p>Guardian verification is required before authorizing or controlling a Player. Contact the app operator through your existing beta invitation contact. Verification uses a reviewed consent form, verification call, or approved verification provider. Do not upload identity documents into feedback.</p>}
 {retention&&<p>{retention.enabled?'Inactivity deletion is enabled. Warnings arrive after six months and at least 30 days before deletion after 12 months.':'Inactivity deletion is not enabled yet.'} Last activity: {new Date(retention.lastActivity).toLocaleDateString()}. Player or linked parent activity keeps this Player active.</p>}
 {status&&<><p><b>{status.paused?'Collection paused':status.collectionAllowed?'Player authorized':'Guardian authorization required'}</b> · {status.requiresGuardian?'Under-18 privacy protection':'Adult Player'} · {status.parentCount} linked parent{status.parentCount===1?'':'s'}.</p>
 {role==='Parent'&&status.guardianVerified&&<><label className="privacyConsentCheck"><input type="checkbox" checked={authorization} onChange={e=>setAuthorization(e.target.checked)}/><span>I am authorized to act for this Player. I have read the Privacy Notice and authorize collection for the app. Photos are optional; Coach sharing is a separate choice.</span></label><button disabled={busy||!authorization} onClick={()=>void run(()=>client.rpc('privacy_authorize_player',{p_athlete:id}))}>Authorize this Player</button></>}
 <div className="privacyActionGrid"><button disabled={busy||!status.canControl} onClick={download}>Download Player Data</button>
 <button disabled={busy||!status.canControl||(status.paused&&((!authorization&&status.requiresGuardian)||status.withdrawalByAnotherGuardian))} onClick={()=>void run(()=>client.rpc('privacy_pause_player',{p_athlete:id,p_paused:!status.paused}))}>{status.paused?'Resume Collection':'Stop Collection & Withdraw Consent'}</button>
 <button disabled={busy||!status.canControl} onClick={()=>void run(()=>client.rpc('privacy_remove_photo',{p_athlete:id}))}>Remove Player Photo</button></div>
 {status.withdrawalByAnotherGuardian&&<p>Another guardian withdrew consent. Operator authority review is required before resuming.</p>}
 <p>Stopping collection immediately blocks cloud workspace access and removes Coach connections. Resuming does not reconnect Coaches. Removing a photo removes stored copies controlled by the app; it cannot erase screenshots or previously downloaded exports.</p>
 {teams.map(t=><div className="rc68PrivacyTeam" key={t.team_id}><b>{t.team_name}</b><button disabled={busy||!status.canControl} onClick={()=>void run(()=>client.rpc('privacy_revoke_coach',{p_athlete:id,p_team:t.team_id}))}>Revoke Coach Access</button></div>)}
 <details><summary>Delete this Player</summary><p>Deletes the Player’s active cloud workspace, photos, history, team links and linked Player login. This cannot be undone. Backups expire according to the operator’s published retention schedule.</p>
 {status.parentCount>1?<><p>This Player has multiple linked parents. Stop collection now, then request deletion for guardian-authority review.</p><button disabled={busy||!status.canControl} onClick={()=>void run(async()=>{const p=await client.rpc('privacy_pause_player',{p_athlete:id,p_paused:true});if(p.error)return p;return client.rpc('submit_privacy_request',{p_request_type:'delete_athlete',p_athlete_id:id,p_details:'Shared guardian deletion request. Collection paused; review guardian authority.'})})}>Pause & Request Reviewed Deletion</button></>:<><label>Type DELETE PLAYER<input autoComplete="off" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><button disabled={busy||!status.canControl||confirm!=='DELETE PLAYER'} onClick={()=>void run(async()=>{const r=await client.rpc('privacy_delete_player',{p_athlete:id,p_confirmation:confirm});if(!r.error&&role==='Player')await onSignOut();return r})}>Permanently Delete Player</button></>}
 </details></>}
 <details><summary>Delete my account</summary><p>Deletes your login, email, personal workspace and account links. Another parent’s account and shared Players remain. Delete or transfer solely managed Players first. For a linked Player account, delete the Player record first or use reviewed deletion.</p>
 <label>Current password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Type DELETE ACCOUNT<input autoComplete="off" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><button disabled={busy||confirm!=='DELETE ACCOUNT'||!password} onClick={deleteAccount}>Permanently Delete My Account</button></details>
 {message&&<p role="status">{message}</p>}
 </section>;
}
export function GuardianVerificationAdmin({client,parents}:{client:SupabaseClient;parents:{user_id:string;display_name:string;email:string}[]}){
 const [id,setId]=useState(''),[method,setMethod]=useState('signed_form'),[reference,setReference]=useState(''),[checked,setChecked]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 return <section className="rc68PrivacyControls"><h3>Guardian verification review</h3><p>Record verification only after reviewing guardian authority and completing the approved consent process. This is a manual decision, not automatic legal certification. Store documents with your restricted verification provider; enter only an opaque reference here.</p><label>Parent<select value={id} onChange={e=>setId(e.target.value)}><option value="">Choose Parent</option>{parents.map(p=><option key={p.user_id} value={p.user_id}>{p.display_name||p.email}</option>)}</select></label><label>Method<select value={method} onChange={e=>setMethod(e.target.value)}><option value="signed_form">Reviewed signed consent form</option><option value="video_call">Documented verification call</option><option value="approved_provider">Approved verification provider</option></select></label><label>Evidence reference<input maxLength={200} value={reference} onChange={e=>setReference(e.target.value)}/></label><label className="privacyConsentCheck"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/><span>I verified this adult’s guardian authority and completed the operator’s reviewed consent process.</span></label><button disabled={busy||!checked||!id||reference.trim().length<3} onClick={async()=>{setBusy(true);const r=await client.rpc('privacy_verify_guardian',{p_user:id,p_method:method,p_reference:reference});setMessage(r.error?.message||'Guardian verification recorded. The Parent must now authorize each Player.');setBusy(false)}}>Record Verification</button>{message&&<p role="status">{message}</p>}</section>;
}
export function ReviewedPrivacyActions({client,players}:{client:SupabaseClient;players:{id:string;name:string}[]}){
 const [id,setId]=useState(''),[reference,setReference]=useState(''),[confirm,setConfirm]=useState(''),[action,setAction]=useState('delete'),[age,setAge]=useState('18'),[checked,setChecked]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 return <section className="rc68PrivacyControls"><h3>Reviewed guardian requests</h3><p>Resolve conflicting guardian authority before deleting shared Player records or resuming after another guardian’s withdrawal. Keep evidence with the restricted verification provider. Record only an opaque reference.</p><label>Player<select value={id} onChange={e=>{setId(e.target.value);setChecked(false)}}><option value="">Choose Player</option>{players.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Reviewed action<select value={action} onChange={e=>{setAction(e.target.value);setChecked(false);setConfirm('')}}><option value="delete">Erase shared Player</option><option value="resume">Resolve withdrawal and resume</option><option value="adult">Confirm adulthood for privacy authorization</option></select></label>{action==='adult'&&<label>Verified adult age<input type="number" min="18" max="100" value={age} onChange={e=>setAge(e.target.value)}/></label>}<label>Authority review reference<input maxLength={200} value={reference} onChange={e=>setReference(e.target.value)}/></label><label className="privacyConsentCheck"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/><span>I reviewed guardian authority and any conflicting requests, and have evidence authorizing this action.</span></label>{action==='delete'&&<label>Type DELETE PLAYER<input value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="off"/></label>}<button disabled={busy||!checked||!id||reference.trim().length<10||(action==='delete'&&confirm!=='DELETE PLAYER')} onClick={async()=>{setBusy(true);const r=action==='delete'?await client.rpc('privacy_reviewed_player_delete',{p_athlete:id,p_reference:reference,p_confirmation:confirm}):action==='resume'?await client.rpc('privacy_review_resume',{p_athlete:id,p_reference:reference}):await client.rpc('privacy_review_adult',{p_athlete:id,p_age:Number(age),p_reference:reference});setMessage(r.error?.message||'Reviewed action completed. Refresh account diagnostics.');setBusy(false)}}>Complete Reviewed Action</button>{message&&<p role="status">{message}</p>}</section>;
}
export function PrivacyAdminSecurity({client}:{client:SupabaseClient}){
 const [level,setLevel]=useState('checking'),[factor,setFactor]=useState(''),[qr,setQr]=useState(''),[code,setCode]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let alive=true;Promise.all([client.auth.mfa.getAuthenticatorAssuranceLevel(),client.auth.mfa.listFactors()]).then(([a,f])=>{if(!alive)return;setLevel(a.data?.currentLevel||'aal1');setFactor(f.data?.totp?.find(x=>x.status==='verified')?.id||'')});return()=>{alive=false}},[client]);
 return <section className="rc68PrivacyControls"><h3>Admin privacy security</h3>{level==='aal2'?<p>Authenticator verified for this session. Privacy decisions still require reviewed guardian-authority evidence.</p>:<><p>Guardian verification, shared Player deletion and authority-review decisions require an authenticator check.</p>{!factor&&<button disabled={busy} onClick={async()=>{setBusy(true);const r=await client.auth.mfa.enroll({factorType:'totp',friendlyName:'Elite Performance Admin'});if(r.error)setMessage(r.error.message);else{setFactor(r.data.id);setQr(r.data.totp.qr_code)}setBusy(false)}}>Set Up Authenticator</button>}{qr&&<><img src={qr} alt="Scan this private setup code with your authenticator" style={{width:220,maxWidth:'100%'}}/><p>Scan with your authenticator. Keep its recovery arrangements private.</p></>}{factor&&<><label>Authenticator code<input inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/></label><button disabled={busy||code.length!==6} onClick={async()=>{setBusy(true);const r=await client.auth.mfa.challengeAndVerify({factorId:factor,code});setCode('');if(r.error)setMessage(r.error.message);else{setQr('');setLevel('aal2');setMessage('Authenticator verified.')}setBusy(false)}}>Verify Authenticator</button></>}</>}{message&&<p role="status">{message}</p>}</section>;
}
